# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lm0smqaCxYZHAR3UbDvjOJCPZyeZdA_v

ESTRUCTURA Y FUNCIONES
"""

def calcular_bono(sueldo, rendimiento):
    if rendimiento >= 90:
        return sueldo * 0.20
    elif rendimiento >= 75:
        return sueldo * 0.10
    else:
        return 0

sueldo = float(input("Ingrese el sueldo base: "))
rendimiento = int(input("Ingrese el porcentaje de rendimiento: "))

bono = calcular_bono(sueldo, rendimiento)
print(f"El bono es: {bono}")
print(f"Sueldo total: {sueldo + bono}")