# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i1k8OELzESSuOrmgbyaTDutBlovDC-cK

Función con retorno de valor
"""

def calcular_area(base, altura):
    return base * altura

base = float(input("Ingrese la base: "))
altura = float(input("Ingrese la altura: "))

area = calcular_area(base, altura)
print(f"El área del rectángulo es: {area}")