# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fzWe8OLbL07BZV-pC5C_zWQcTt-TePsC

Uso de variables locales y globales
"""

contador = 0  # variable global

def incrementar():
    global contador
    local = 5  # variable local
    contador += local
    print(f"Contador actual: {contador}")

incrementar()
incrementar()
incrementar()